# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- pavan

pool:
  vmImage: ubuntu-latest

variables:
  mavenOptions: '-Xmx3072m'



steps:
- checkout: self



- script: |
    echo " running cucumber tests with specific tag "
    mvn clean test \
      -Dcucumber.options="src/test/java/feature/placevalidations.feature"
      
  displayName:  'AutomationTestCases'
      

    
    
- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    mergeTestResults: true
    failTaskOnFailedTests: false