# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
  push:
    branches: [ "test" ]
  pull_request:
    branches: [ "test" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Create testoutput directory
      run: mkdir -p /home/runner/work/autdemo/autdemo/target
      
    - name: install maven
      run: mvn test -Dcucumber.filter.tags="@regression"
        

    - name: Upload HTML report as Artifact
      uses: actions/upload-artifact@v4
      with:
          name: test-output
          path: ./target

    

    - name: Get Jira-xray api token
      id: xray-auth
      run: |
            TOKEN=$(curl -X POST -H "Content-Type: application/json" \
            -d '{"client_id":"${{ secrets.XRAY_CLIENT_ID }}","client_secret":"${{ secrets.XRAY_CLIENT_SECRET }}"}' \
            "https://xray.cloud.getxray.app/api/v2/authenticate")
            echo "XRAY_TOKEN=$(echo $TOKEN | tr -d '"')" >> $GITHUB_ENV
    - name: Upload Test Results to Xray
      run: |
        curl -H  "Content-Type: text/xml" \
               -H "Authorization: Bearer $XRAY_TOKEN" \
               --data @"**/surefire-reports/TEST-*.xml" \
               -X POST \
               "https://xray.cloud.getxray.app/api/v2/import/execution/testng?projectKey=TES"
     

    - name: Submit results to Xray
      uses: mikepenz/xray-action@v2.4.5
      with:
        username: ${{ secrets.XRAY_CLIENT_ID }}
        password: ${{ secrets.XRAY_CLIENT_SECRET }}
        testFormat: "junit"
        testPaths: "**/surefire-reports/TEST-*.xml"
        projectKey: "TES"

    
