
name: Java CI with maven

on:
  push:
    branches: [ "test" ]
  pull_request:
    branches: [ "test" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Create testoutput directory
      run: mkdir -p ./target
      
    - name: install maven
      run: mvn clean install || true
        

    - name: Upload HTML report as Artifact
      uses: actions/upload-artifact@v4
      with:
          name: test-output
          path: ./target

    - name: Get Jira-xray api token
      id: xray-auth
      run: |
            TOKEN=$(curl -X POST -H "Content-Type: application/json" \
            -d '{"client_id":"${{ secrets.XRAY_CLIENT_ID }}","client_secret":"${{ secrets.XRAY_CLIENT_SECRET }}"}' \
            "https://xray.cloud.getxray.app/api/v1/authenticate")
            echo "XRAY_TOKEN=$(echo $TOKEN | tr -d '"')" >> $GITHUB_ENV
    - name: Upload Test Results to Xray
      run: |
          curl -H  "Content-Type: application/json" \
               -H "Authorization: Bearer $XRAY_TOKEN" \
               --data @"./target/cucumber.json" \
               -X POST \
               "https://xray.cloud.getxray.app/api/v1/import/execution/cucumber?projectKey=TES&testExecKey=TES-52"
    
