name: Sync GitHub Issues with Jira

on:
  issues:
    types: [opened, edited]

jobs:
  sync_with_jira:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Create Jira issue
      if: contains(github.event.issue.labels.*.name, 'bug')
      run: |
        curl -X POST -H "Content-Type: application/json" \
        -H "Authorization: Basic ${{ secrets.JIRAAPI }}" \
        -d '{
              "fields": {
                "project": {
                  "key": "TES"
                },
                "summary": "${{ github.event.issue.title }}",
                "description": "${{ github.event.issue.body }}",
                "issuetype": {
                  "name": "Bug"
                }
              }
            }' \
        https://YOUR_JIRA_DOMAIN/rest/api/2/issue/
      env:
        JIRA_AUTH: ${{ secrets.JIRAAPI }}
